### ISSUE TITLE
New firmware GWM-07.027-03_GCW-10.22-05.7

### ISSUE THREAD

**Issue by emlynmac** [djiesr/ocpp#3]
Grizzl-e have released a new version of the firmware which seems to work a little more to the protocol standard.
It disconnects with this fork of the repo / previous update instructions.

With the original version, it now at least shows some values and works for a few seconds before disconnecting permanently.

I'll provide some more logs when I get a chance, but for others who want to use this fork - this firmware is not working for me.

**Comment by devzwf** [comment]
Hi
thanks for the update 
i did not upgrade since i was afraid of this situation

let us know

**Comment by devzwf** [comment]
and  i would like to found the release note as well

**Comment by emlynmac** [comment]
@devzwf the only release notes I could find are:

Version GWM-07.027-03_GCW-10.22-05.7 is available for your Grizzl-E Smart

Changelog:

-More flexible scheduling with current adjustment (OCPP Smart Charging Profile) has been introduced.

-Connection to OCPP server via unsecured WiFi network has been enabled.

-Updated Configuration page.

**Comment by djiesr** [comment]
Do you have a update since this one?

**Comment by emlynmac** [comment]
@djiesr, I've not had time to dig into the details here yet. Still on my list, hopefully next week I'll have some time!

**Comment by emlynmac** [comment]
OK, had some time to play this morning.

First off, any mods to OCPP need to be done under python3.12 as that is my HASS version:
.
Before install the integration, copy de "ocpp" folder of this [OPCC package](https://github.com/mobilityhouse/ocpp) in your "HA Config"/deps/lib/python3.1**2**/site-packages/

After that, using just the _stock_ OCPP HASS version from [here](https://github.com/lbbrhzn/ocpp) gets the following:

```
2024-11-15 09:18:56.099 INFO (MainThread) [ocpp] GRIZZL-E: send [2,"429d7104-2cc9-4842-a33a-969c116e6e8e","GetConfiguration",{"key":["MeterValuesSampledData"]}]
2024-11-15 09:18:56.272 INFO (MainThread) [ocpp] GRIZZL-E: receive message [3,"429d7104-2cc9-4842-a33a-969c116e6e8e",{"configurationKey":],"unknownKey":["MeterValuesSampledData"]}]
2024-11-15 09:18:56.273 ERROR (MainThread) [ocpp] Unable to parse message: '[3,"429d7104-2cc9-4842-a33a-969c116e6e8e",{"configurationKey":],"unknownKey":["MeterValuesSampledData"]}]', it doesn't seem to be valid OCPP: FormatViolationError: Payload for Action is syntactically incorrect or structure for Action,  {'cause': 'Message is not valid JSON', 'ocpp_message': '[3,"429d7104-2cc9-4842-a33a-969c116e6e8e",{"configurationKey":],"unknownKey":["MeterValuesSampledData"]}]'}
Traceback (most recent call last):
  File "/config/deps/lib/python3.12/site-packages/ocpp/messages.py", line 83, in unpack
    msg = json.loads(msg)
          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 63 (char 62)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/deps/lib/python3.12/site-packages/ocpp/charge_point.py", line 258, in route_message
    msg = unpack(raw_msg)
          ^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/ocpp/messages.py", line 85, in unpack
    raise FormatViolationError(
ocpp.exceptions.FormatViolationError: FormatViolationError: Payload for Action is syntactically incorrect or structure for Action,  {'cause': 'Message is not valid JSON', 'ocpp_message': '[3,"429d7104-2cc9-4842-a33a-969c116e6e8e",{"configurationKey":],"unknownKey":["MeterValuesSampledData"]}]'}
```

And this has the charger in a reboot loop after that.

I'll spend a little time investigating and see if I can progress it.

**Comment by djiesr** [comment]
Try to use my fork: https://github.com/djiesr/ocpp/releases/tag/v0.1.7.500 
I have to merge it with the last ocpp, but it still work well.

**Comment by emlynmac** [comment]
Using this fork, there are other issues.

There are warnings present:
```
Logger: py.warnings
Source: deps/lib/python3.12/site-packages/ocpp/v16/call.py:428
First occurred: 9:45:33 AM (1 occurrences)
Last logged: 9:45:33 AM

/config/deps/lib/python3.12/site-packages/ocpp/v16/call.py:428: UserWarning: GetConfigurationPayload is deprecated, use instead GetConfiguration warnings.warn(

Logger: py.warnings
Source: deps/lib/python3.12/site-packages/ocpp/v16/call_result.py:396
First occurred: 9:45:33 AM (1 occurrences)
Last logged: 9:45:33 AM

/config/deps/lib/python3.12/site-packages/ocpp/v16/call_result.py:396: UserWarning: StatusNotificationPayload is deprecated, use instead StatusNotification warnings.warn(

Logger: py.warnings
Source: deps/lib/python3.12/site-packages/ocpp/v16/call_result.py:279
First occurred: 9:45:32 AM (1 occurrences)
Last logged: 9:45:32 AM

/config/deps/lib/python3.12/site-packages/ocpp/v16/call_result.py:279: UserWarning: BootNotificationPayload is deprecated, use instead BootNotification warnings.warn(

```

And from HASS
```
Logger: homeassistant.const
Source: helpers/deprecation.py:222
First occurred: 9:43:29 AM (3 occurrences)
Last logged: 9:44:17 AM

TIME_MINUTES was used from ocpp, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.MINUTES instead, please report it to the author of the 'ocpp' custom integration
POWER_KILO_WATT was used from ocpp, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.KILO_WATT instead, please report it to the author of the 'ocpp' custom integration
ELECTRIC_CURRENT_AMPERE was used from ocpp, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricCurrent.AMPERE instead, please report it to the author of the 'ocpp' custom integration
```

Probably updating with the changes from upstream will remove these?

There's also a hard stop with the configuration:

```
Unexpected exception in connection to 'GRIZZL-E': 'TypeConstraintViolationError: Payload for Action is syntactically correct but at least one of the fields violates data type constraints (e.g. “somestring”: 12), {'cause': "2 is not of type 'string'", 'ocpp_message': <CallResult - unique_id=ec33d7d6-653b-42ab-8a2f-3084ec3a11ef, action=GetConfiguration, payload={'configurationKey': [{'key': 'DipSwitchCurrentLimit', 'readonly': True, 'value': '40'}, {'key': 'MinCurrent', 'readonly': True, 'value': '8'}, {'key': 'StartChargingAfterConnect', 'readonly': False, 'value': 'true'}, {'key': 'AuthorizeRemoteTxRequests', 'readonly': False, 'value': 'true'}, {'key': 'ConnectorPhaseRotation', 'readonly': True, 'value': 'NotApplicable'}, {'key': 'HeartbeatInterval', 'readonly': False, 'value': '3600'}, {'key': 'LocalAuthorizeOffline', 'readonly': False, 'value': 'true'}, {'key': 'LocalPreAuthorize', 'readonly': False, 'value': 'true'}, {'key': 'MeterValueSampleInterval', 'readonly': False, 'value': '20'}, {'key': 'NumberOfConnectors', 'readonly': True, 'value': '1'}, {'key': 'ResetRetries', 'readonly': True, 'value': '1'}, {'key': 'StopTransactionOnInvalid', 'readonly': False, 'value': 'false'}, {'key': 'SupportedFeatureProfiles', 'readonly': True, 'value': 'Core,FirmwareManagement,SmartCharging'}, {'key': 'UnlockConnectorOnEVSideDisconnect', 'readonly': False, 'value': 'false'}, {'key': 'StationPassword', 'readonly': False, 'value': 'LetMeIn!'}, {'key': 'ServerUrl', 'readonly': False, 'value': 'wss://home-assistant.home.bolton-consulting.org:9000/'}, {'key': 'ChargeProfileMaxStackLevel', 'readonly': True, 'value': 2}, {'key': 'ChargingScheduleAllowedChargingRateUnit', 'readonly': True, 'value': 'Current'}, {'key': 'ChargingScheduleMaxPeriods', 'readonly': True, 'value': 1}, {'key': 'MaxChargingProfilesInstalled', 'readonly': True, 'value': 2}]}>}'
```
Looking at the schema, it's expecting the response to be a string.

~After this, I don't have a connected charger.~

EDIT: I do; the charger needed a reboot.... It seems to work without any changes to the OCPP python now; although the reconnects just keeps going up every 30s.

It looks like the reconnect happens from a timeout on the get configuration:

```
Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/deps/lib/python3.12/site-packages/ocpp/charge_point.py", line 427, in call
    response = await self._get_specific_response(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ocpp/api.py", line 898, in _get_specific_response
    resp = await super()._get_specific_response(unique_id, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/ocpp/charge_point.py", line 463, in _get_specific_response
    response = await asyncio.wait_for(self._response_queue.get(), timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/ocpp/api.py", line 428, in post_connect
    await self.get_supported_features()
  File "/config/custom_components/ocpp/api.py", line 505, in get_supported_features
    resp = await self.get_configuration(ckey.supported_feature_profiles.value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ocpp/api.py", line 808, in get_configuration
    resp = await self.call(req)
           ^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/ocpp/charge_point.py", line 431, in call
    raise asyncio.TimeoutError(
TimeoutError: Waited 30s for response on [2,"0c881e99-ffe8-4e40-ba2a-1d347503b97e","GetConfiguration",{}].
```

I can get the schema to pass by relaxing the `GetConfigurationResponse.json`:

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "GetConfigurationResponse",
    "type": "object",
    "properties": {
        "configurationKey": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "key": {
                        "type": "string",
                        "maxLength": 50
                    },
                    "readonly": {
                        "type": "boolean"
                    },
                    "value": {
                        "type": **["integer","string"]**,
                        "maxLength": 500
                    }
                },
                "additionalProperties": false,
                "required": [
                    "key",
                    "readonly"
                ]
            }
        },
        "unknownKey": {
            "type": "array",
            "items": {
                "type": "string",
                "maxLength": 50
            }
        }
    },
    "additionalProperties": true
}
```

**Comment by emlynmac** [comment]
@djiesr It seems happier now with the int/string relax. No more reconnects every 30s!

So to get this firmware happy:

* Copy OCPP to python3.12 local overrides
* Change only the above schema

**Comment by djiesr** [comment]
Good new. For the deprecated constant, i have to update the fork from the main, I will do that in the next month. After this, I will do the correction for the error. 
If it work for now for you, i think the error will not cause some problem.

**Comment by emlynmac** [comment]
> Good new. For the deprecated constant, i have to update the fork from the main, I will do that in the next month. After this, I will do the correction for the error. If it work for now for you, i think the error will not cause some problem.

Which error are you talking about here - the JSON validation? I think this is coming from the Grizzl-e, so it may note be something that can be 'fixed' here?

**Comment by djiesr** [comment]
I have sometimes, I have note them.

**Comment by emlynmac** [comment]
Looks like with the latest HA OS they moved python from 3.12 -> 3.13. Need to ensure the OCPP package changes are moved too...

**Comment by djiesr** [comment]
I will check this weekend if I can connect to my Grizzl-E, it hasn’t worked for a few days. The charging station doesn't even have an IP address anymore.

**Comment by djiesr** [comment]
Ok, my charger is back. I will restart the next update from the last package of lbbrhzn/ocpp and the last update of Grizzl-E. I'm a little buzy, but I thinks I will do that for the first week-end of january.

**Comment by mattbatt** [comment]
Hey djiesr how's it going?  I just found your fork and it looks like I'm on the new firmware. Any updates?
